[workspace]
resolver = "2"
members = ["core", "cli"]

[workspace.package]
version = "0.0.1-beta"
edition = "2021"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Nostradamus: constellation simulation and prediction"
homepage = "https://github.com/nav-solutions/"
repository = "https://github.com/nav-solutions/nostradamus"
categories = ["science", "simulation"]
keywords = ["geo", "navigation", "timing"]
license = "AGPL-3.0-or-later"
readme = "README.md"
exclude = ["data/*", "tools/*"]

[workspace.dependencies]
anise = "0.5"
hifitime = "4"
gnss-rs = "2.5"
nyx-space = "2.1"
thiserror = "1"
rinex = { version = "0.21", features = ["flate2", "nav"] }
sp3 = { version = "1.4", features = ["flate2", "nyx-space"] }
nostradamus-core = { version = "0.0.1-alpha", path = "core" }

[profile.release]
lto = "thin"
codegen-units = 1
