[package]
name = "nostradamus-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
description = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-ars = ["--cfg", "docrs", "--generate-link-to-definition"]

[package.metadata]
msrv = "1.83"

[features]
default = ["dep:rinex", "dep:sp3"] # rinex and SP3 preset by default

[dependencies]
anise = { workspace = true }
gnss-rs = { workspace = true }
hifitime = { workspace = true }
nyx-space = { workspace = true }
sp3 = { workspace = true, optional = true }
rinex = { workspace = true, optional = true }
