[package]
name = "nostradamus-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
description = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-ars = ["--cfg", "docrs", "--generate-link-to-definition"]

[package.metadata]
msrv = "1.83"

[features]
default = ["rinex", "sp3"] # rinex and SP3 presets by default

# SP3 preset and scenarios from text file
sp3 = ["dep:sp3"]

# RINEX preset and scenarios from text file
rinex = ["dep:rinex"]

[dependencies]
anise = { workspace = true }
gnss-rs = { workspace = true }
hifitime = { workspace = true }
nyx-space = { workspace = true }
thiserror = { workspace = true }
sp3 = { workspace = true, optional = true }
rinex = { workspace = true, optional = true }
